spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - RewritePath=SetPath=/
        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#  application:
#    name: api-gateway-service
#server:
#  port: 8081
