spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8084/
            predicates:
              - Path=/api/books/**
          - id: r2
            uri: http://localhost:8083/
            predicates:
              - Path=/api/users/**
          - id: r3
            uri: http://localhost:8085/
            predicates:
              - Path=/api/orders/**
          - id: r4
            uri: http://localhost:8082/
            predicates:
              - Path=/
  application:
    name: api-gateway-service
server:
  port: 8081
